[build]
  command = ""
  functions = "netlify/functions"
  publish = "."
  
  # Ignore builds when only data files change
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- . ':!trips.json' ':!photos/'"

[build.environment]
  NODE_VERSION = "18"

# Function configuration  
[functions]
  directory = "netlify/functions"
  
# Specific function configurations
[[functions]]
  name = "upload-photos"
  timeout = 900  # 15 minutes (max for paid plans)
  memory = 1024  # 1GB memory
  
# Upload endpoint with longer timeout
[[redirects]]
  from = "/.netlify/functions/upload-photos"
  to = "/.netlify/functions/upload-photos"
  status = 200
  headers = {"X-Robots-Tag" = "noindex"}
  
# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"